services:
  notification-api:
    build:
      context: ./NotificationAPI
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_GCHeapHardLimit=1G
      - COMPlus_ThreadPool_ForceMinWorkerThreads=100
      - COMPlus_ThreadPool_ForceMaxWorkerThreads=500

  mongodb:
    image: mongo:latest
    command: mongod --wiredTigerCacheSizeGB 1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
